# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password: nobu19960916
  username: tetetearraio916
  host: tetetearraio916-web.c4gickllylxl.ap-northeast-1.rds.amazonaws.com

production:
  <<: *default
  database: TETETE_portfolio1
